platzigram/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views as local_views


urlpatterns = [
    path('admin', admin.site.urls),

    # Examples don't remove
    path('hello-world/', local_views.hello_world, name='hello_world'),
    path('sorted/', local_views.hi, name='sorted'),
    path('hi/<str:name>/<int:age>', local_views.say_hi, name='hi'),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLS"""
from django.urls import path

from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),
    path(
        route="posts/new",
        view=views.create_posts,
        name="create"
    ),
]

users/urls.py
"""Users URLS"""
from django.urls import path

from users import views
from django.views.generic import TemplateView


urlpatterns = [

    # Posts
    path(
        route='profile/<str:username>',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # Management
    path(
        route='users/login/', 
        view=views.login_view,
        name='login'
    ),
    path(
        route='users/logout/',
        view=views.logout_view,
        name='logout'
    ),
    path(
        route='users/signup/',
        view=views.signup,
        name='signup'
    ),
    path(
        route='users/me/profile/', 
        view=views.update_profile,
        name='update'
    )
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock %}
    </div>
</body>
</html>

templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
    {% load static %}
    <nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
        <div class="container">

            <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
                <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
            </a>

            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item">
                        <a href="">
                            {% if request.user.profile.picture %}
                                <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                            {% else %}
                                <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                            {% endif %}
                        </a>
                    </li>

                    <li class="nav-item nav-icon">
                        <a href="{% url 'posts:create' %}">
                            <i class="fas fa-plus"></i>
                        </a>
                    </li>

                    <li class="nav-item nav-icon">
                        <a href="{% url 'users:logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</body>
</html>